Feat/Users Api validations and authentification
PaoBrs/vocationalTestApp-API pull request #5
Opened 2022-03-31 02:52 UTC by eastor112

### Description

Implement local authenticatión ('/auth/local/login')
Implement all validations in api users

### Feeling

- [ ] 🤙 Quick fix
- [x] 👌 Done and ready
- [ ] 🤞 Hope it works, please review carefully

### Tickets

G1MAV-134-Implement validations in users API and local authentification in back project

### Scope

- [ ] 🐞 Bugfix (non-breaking changes que resuelve un problema
- [x] 💚 Improve (non-breaking change)
- [x] ⚡️ New feature (non-breaking change)
- [ ] ⚠️ Breaking change

2022-03-31 21:27 UTC, mhbuiles requested changes

2022-03-31 21:27 UTC, mhbuiles commented on .eslintrc.json
>  }
Para qué guardar esa imagen en el proyecto? Debemos evitar subir muchas imágenes a los repositorios, no es necesario tener este ERD en el repositorio del proyecto.

2022-03-31 21:38 UTC, eastor112 commented on .eslintrc.json
>  }
Listo, ya lo eliminé

2022-04-02 19:24 UTC, PaoBrs approved these changes
![](https://giphy.com/gifs/molangofficialpage-clap-bravo-2lQCBjuFMLCOvXno4l)

2022-04-03 16:57 UTC, merged